<!DOCTYPE html>
<html lang="zh-CN">
	<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
<!-- Header part	 -->
<?php include_once "../header.phtml";?>

<p>Test222</p>



<script type="text/javascript" src="/common/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="/common/jquery-extend/jquery-util.js"></script>
<script type="text/javascript" src="/common/bootstrap/3.3.4/bootstrap.min.js"></script>
</body>
</html>